# -*- coding: utf-8 -*-
GRAVITY = 0.0007
LEFT = -1
RIGHT = 1
SPRITE_IDLE = 0
SPRITE_WALKING = 1
SPRITE_JUMPING = 2
SPRITE_SHOOTING = 3
SPRITE_MELEEING = 4
SPRITE_DAMAGE = 5
SPRITE_DYING = 6
ANCHO_PANTALLA = 800
ALTO_PANTALLA = 600


MELEE_VISION_RANGE = 300
MELEE_ATTACK_RANGE =10
RANGED_VISION_RANGE = 320
RANGED_SCAPE_VISION = 150	

'''
VELOCIDAD_JUGADOR = 0.2 # Pixeles por milisegundo
VELOCIDAD_SALTO_JUGADOR = 0.3 # Pixeles por milisegundo
'''
